
    <div class="page-404">
        <div class="container404-">

            <div>
            <h1 class="title-404">404</h1>
            <h3 class="">Page non trouvée</h3>

            </div>


            <div class="texte-404">
                <p>
                La page que vous tentez d'afficher n'existe pas ou une autre erreur s'est produite.

                </p>
            </div>
            <div class="texte-404">
                <p>
                Vous pouvez revenir à <a href="?Page=homePage">la page d'accueil</a>.

                </p>
            </div>

        </div>
    </div>
