<div class='gamelist'>
<div>
<h3>Liste des jeux</h3>
</div>

<ul>
    <?php foreach ($Games as $Game) : ?>
        <ul>
            <li>
                <a class="link text-orange " href="?page=gamePage&id=<?= htmlentities($Game->getId()) ?>">
                    <?= htmlentities($Game->getGameName()) ?>
                </a>
            </li>
            <br>
            <li class="text-white" >
                <?= htmlentities($Game->getContent()) ?>
            </li>
            <br>

            <li class="text-white">
                <?= htmlentities($Game->getCategory()) ?>
            </li>

        </ul>
        <br><br>
    <?php endforeach; ?>
</ul>

</div>
