<div class="carousel">
  <div class="slides">
    <img src="../styles/image/link.jpg" alt="slide image" class="slide">
    <img src="../styles/image/ff6.jpg" alt="slide image" class="slide">
    <img src="../styles/image/tourbillon.jpg" alt="slide image" class="slide">
    <img src="../styles/image/bouclier.jpg" alt="slide image" class="slide">

  </div>
  <div class="controls">
    <div class="control prev-slide">&#9668;</div>
    <div class="control next-slide">&#9658;</div>
  </div>
</div>

<h3><?= $Game->getGameName() ?></h3>

<ul>
    <li>
        <?= $Game->getCategory() ?>
    </li>
    <li>
        <?= $Game->getContent() ?>
    </li>
    <button type="button">
        <a href="<?= htmlentities($Game->getLink()) ?>" target="_blank">
            jouer
        </a>
    </button>
</ul>
<form action="" method="post">
    <label for="comment">laisser votre commentaire sur le jeu </label>
    <textarea name="comment" id="" cols="60" rows="8"></textarea>
    <button type="submit" href="?page=gamePage&id=<?= htmlentities($Game->getId()) ?>">Publier</button>
</form>

<table>

    <thead>
        <tr>
            <th colspan="2">Comentaires des utilisateurs</th>
        </tr>
    </thead>

    <tbody>

        <?php
        foreach ($rawData as $data) : ?>
            <tr>
                <td><?= htmlentities($data['comment']) ?></td>
                <td><?= htmlentities($data['lastName']) ?></td>
            </tr>
        <?php endforeach; ?>

    </tbody>

</table>