<h3 class="lightWord">Ajouter votre jeu</h3>

<div class="addGame">

    <div class="form">
        <form class="addGameForm-form" method="POST">
            <input type="text" name="gameName" placeholder="Nom du jeu">
            <input type="text" name="link" placeholder="Lien du jeu " placeholder="Coller le lien du jeu">
            <input type="textarea" name='content' placeholder="Description du jeu ">
            <input type="text" name="category" placeholder="Genre ">
            <button type="submit">Enregistrer </button>
        </form>

    </div>
</div>