<form action="" method="POST">
    <input type="text" name="gameName" placeholder="Nom de votre jeu">
    <input type="text" name="link" placeholder="Lien du jeu " placeholder="Coller le lien du jeu">
    <input type="textarea" name='content' placeholder="Quelques mots à porpos de votre jeu " >
    <input type="text" name="category" placeholder="Genre de votre jeu " >
    <input type="submit" value='Enregister le jeu ' >

</form>