 <h3>Connexion </h3>

 <div>
   <form method="POST">
     <div>
       <label for="email"></label>
       <input type="text" name="email" placeholder="Votre adresse e-mail" />

       <label for="password"></label>
       <input type="password" name="password" placeholder="Votre mot de passe" />
     </div>

     <div>
       <input type="submit" value="Se connecter" />
     </div>
   </form>

   <div>
     vous n'avez pas encore de compte ? <a href="?page=register">s'inscrire</a>
   </div>
 </div>