<div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="?page=homepage"?>">HomePage</a>
                    </li>
                    <?php if (!isset($_SESSION['user_id'])) : ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="?page=login">Connexion</a>
                        </li>
                    <?php else : ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="?page=gameList">Jeux</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href=""><?= htmlentities($User->getLastName()) ?></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="">Se déconnecter</a>
                        </li>
                    <?php endif; ?>

                </ul>
            </div>
