<h3 class="lightWord">Inscription</h3>


<div class="login">
  <div class="form">
    <form class="login-form" method="POST">
      <input type="text" name="firstName" placeholder="Nom">
      <input type="text" name="lastName" placeholder="Prénom">
      <input type="text" name="email" placeholder="Email" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" required />
      <input type="password" name="password1" placeholder="Mot de passe" required />
      <input type="password" name="password2" placeholder="Confirmer mot de passe" required />

      <select type="text" name="status" id="" placeholder=" Statut">
        <option value="">Choisissez votre statut </option>
        <option value="Utilisateur">Utilisateur</option>
        <option value="Createur de contenu">Créateur de contenu </option>
      </select>


      <button type="submit">S'enregistrer</button>
    </form>

  </div>
</div>