<h3 class="lightWord"> COMPTE </h3>



<div class="userPage">
    <div class="form">

        <form class="userPage-form" method="POST">
            <input type="text" name="firstName" value="<?= htmlentities($User->getFirstName()) ?>">
            <input type="text" name="lastName" value="<?= htmlentities($User->getLastName()) ?>">
            <input type="text" name="email" value="<?= htmlentities($User->getEmail()) ?>">
            <button type="submit"><a class="white-link" href="?page=personalUpDate&id=<?= htmlentities($User->getId()) ?>">Modifier</a></button>
        </form>
        <br>
        <?php

        if ($_SESSION['user_status'] === 'admin') : ?>
            <button type="submit"> <a class="white-link" href="?page=adminPage">Liste des utilisateurs</a> </button> <br>
        <?php endif; ?>

    </div>
</div>