<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="../style/style.css">
    <link rel="stylesheet" href="../styles/css/style.css">

    <title>Game.Gate</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary ">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="?page=homepage">HomePage</a>
                    </li>
                    <?php if (!isset($_SESSION['user_id'])) : ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="?page=login">Connexion</a>
                        </li>
                    <?php else : ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="?page=gameList">Jeux</a>
                        </li>

                        </li>
                        <?php if ($_SESSION['user_status'] === 'Createur de contenu' || $_SESSION['user_status'] === 'admin') : ?>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="?page=gameAdd">Ajouter votre jeu </a>
                            </li>
                        <?php endif; ?>


                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="?page=userPage&id=<?= $_SESSION['user_id'] ?>"><?= htmlentities($_SESSION['user_Name']) ?></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="?page=logout">Se déconnecter</a>
                        </li>
                    <?php endif; ?>

                </ul>
            </div>
        </nav>
    </header>

    <main>
        <?php require $template; ?>
    </main>

    <footer>
        $footer
        copyright exclusif
    </footer>
</body>

</html>