<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../styles/feuilles css/rester.scss">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="../styles/css/style.css">

    <title>Game.Gate</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary ">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="?page=homePage">HomePage</a>
                    </li>
                    <?php if (!isset($_SESSION['user_id'])) : ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="?page=login">Connexion</a>
                        </li>
                    <?php else : ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="?page=gameList">Jeux</a>
                        </li>

                        </li>
                        <?php if ($_SESSION['user_status'] === 'Createur de contenu' || $_SESSION['user_status'] === 'admin') : ?>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="?page=gameAdd">Ajouter votre jeu </a>
                            </li>
                        <?php endif; ?>




                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="?page=userPage&id=<?= $_SESSION['user_id'] ?>"><?= htmlentities($_SESSION['user_Name']) ?></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="?page=logout">Se déconnecter</a>
                        </li>
                    <?php endif; ?>

                </ul>
            </div>
        </nav>
        <br>
    </header>

    <main>

        <?php require $template; ?>
    </main>


    <footer class="section bg-footer">
        <div class="container">
            <div>
                <h6 class="footer-heading text-uppercase text-orange">Informations</h6>
                <ul class="footer-link mt-4">
                    <li>
                        <p>Plan du site</p>
                    </li>
                    <li>
                        <p>Nos équipes</p>
                    </li>
                    <li>
                        <p>Conditions d'utilisation</p>
                    </li>
                </ul>
            </div>

            <div id=footlogo>
                <span>
                    <img src="../styles/image/GameGate2.svg" alt="logo">
                </span>
            </div>


            <div class="footer-link">
                <h6 class="footer-heading text-uppercase text-orange">Nous contacter</h6>
                <p class="contact-info mt-4">Besoin d'aide ?</p>
                <p class="contact-info">+336 111-121-314</p>
                :
            </div>
        </div>
        <div class="text-center mt-5">
            <p class="footer-alt">2022 GameGate© Society, All Rights Reserved</p>
        </div>
    </footer>

    <script type="module" src="./main.js"></script>

</body>

</html>